version: 2.1
commands:
  update_badge:
    parameters:
      name:
        description: "filename of badge to update"
        type: string
      value:
        description: "the value to set in badge"
        type: string
    steps:
      - run:
          name: install jq
          cmd: |
            apt-get install -y jq
      - run:
          name: Update badge << parameters.name >>
          cmd: |
            git clone https://${GITHUB_TOKEN}@github.com/ognots/badge-updater.git
            cd badge-updater
            cat << parameters.name >> | jq -r '.message = "<< parameters.value >>"' | tee << parameters.name >>
            git add << parameters.name >>
            git commit -m "badge update bot: update << parameters.name >> to << parameters.value >>"
            git push https://${GITHUB_TOKEN}@github.com/ognots/badge-updater.git

jobs:
  badge_updater:
    docker:
      - image: debian:stretch-slim
    steps:
      - update_badge:
          name: nightly-github.json
          value: updater-success

workflows:
  version: 2
  badge_updater:
    jobs:
      - badge_updater