version: 2.1

commands:
  update_badge:
    parameters:
      filename:
        description: "filename of badge to update"
        type: string
    steps:
      - run:
          name: install jq
          command: |
            apt-get update
            apt-get install -y jq git
      - run:
          name: Update badge << parameters.filename >>
          command: |
            git config --global user.email dev-helper@filecoin.io
            git config --global user.name filecoin-helper
            git clone https://${GITHUB_TOKEN}@github.com/ognots/badges.git
            cd badges
            cat << parameters.filename >> | jq --arg FILECOIN_BINARY_VERSION "${FILECOIN_BINARY_VERSION}" -r '.message = $FILECOIN_BINARY_VERSION}' | tee << parameters.filename >>
            git add << parameters.filename >>
            git commit -m "badge update bot: update << parameters.filename >> to ${FILECOIN_BINARY_VERSION}"
            git push https://${GITHUB_TOKEN}@github.com/ognots/badges.git

jobs:
  badge_updater:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          command: |
            echo "export FILECOIN_BINARY_VERSION="ognots-test"" >> $BASH_ENV
      - update_badge:
          filename: "nightly-github.json"

workflows:
  version: 2
  main:
    jobs:
      - badge_updater